# Generated by Django 5.0.1 on 2024-02-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template', models.TextField()),
                ('placeholder', models.JSONField(default=dict, help_text='Put the placeholder around square bracket.')),
            ],
        ),
    ]
