# Generated by Django 5.0.1 on 2024-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hiken", "0002_alter_templatehtml_placeholder_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templatehtml",
            options={"verbose_name_plural": "HTML Templates"},
        ),
        migrations.AddField(
            model_name="templatehtml",
            name="subject",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
